### ISSUE TITLE
Redundância de nomes

### ISSUE THREAD

**Issue by raphatorres89** [xjhofernandes/RagnarokAPI#2]
Fala meu chapa, blz?
Primeiramente parabéns pela iniciativa, vou usar muito essa api.

Estava dando uma olhadinha, e a api nao tem versão na url, seria bacana colocar um v1 pra evitar quebra de contrato nos payloads.

Outra coisa é os nomes repetidos, por exemplo:
Item: {
  ItemId: ...,
  NameItem: ...,
  ItemDescription: ...,
  ...

Acho que seria bacana e deixaria mais limpo remover as palavras “item” de dentro do objeto item.
Isso acontece pra monster também...
Abraço!

**Comment by xjhofernandes** [comment]
Olá, Rapha. Boa tarde. 

Fiz algumas alterações, como você citou. E ajustei os nomes repetidos (Tanto de monstros, quanto de itens). 
E, também, e tentei versionar a API e deixei a versão v1.0 na URL (isso ainda está em construção) 

Segue os link do heroku com esses ajustes: 
https://ragnarokapi.herokuapp.com/api/v1.0/item/607
https://ragnarokapi.herokuapp.com/api/v1.0/monster/1247

Depois, irei adicionar um domínio para essa API e tirar do heroku. (Estou pensando em deixar tudo em uma máquina lightsail da amazon). Mas, caso tenha alguma outra dica. Só falar! :) 

Muito obrigado pelas dicas!
